### ISSUE TITLE
Plotting a subset of a Multiindex-DataFrame produces wrong legend entries

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#92]
The legend entry for a component looks like `(val, Battery)` instead of `Battery` if I use a subset of the `to_pandas` class. I use a crude workaround.

```python
    new_labels = []
    for lab in labels:
        lab = lab.replace("(val, ", "")
        lab = lab.replace(")", "")
        new_labels.append(lab)
```

Isn't there a way to avoid such wrong entries instead of repairing them afterwards?

**Comment by ckaldemeyer** [comment]
I think this was already solved in a further branch using *axes, handles = blablubb* and somehow got lost..

**Comment by uvchik** [comment]
Isn't it possible to fix it within the slice? That would be good if we want to use it in other places. 

I know that I can manipulate the legend entries afterwards. This is what I did in the example above. Here is the full example:

```python
    handles, labels = ax.get_legend_handles_labels
    new_labels = []
    for lab in labels:
        lab = lab.replace("(val, ", "")
        lab = lab.replace(")", "")
        new_labels.append(lab)
    handles, labels = ax.get_legend_handles_labels
```
I do not want a solution like this in the plotting class because it is very fragile. If somebody wants to use parentheses in his/her legend it will not produce the desired result. But maybe you will have a better idea.

**Comment by ckaldemeyer** [comment]
For the basic pandas plots, the *Index* is set as xticks/axticklabels and the *Column names* are set as Legend entries.

As we are already discussing a restructuring, it might also be an idea to just remove certain levels from the index and unstack the level we want to plot e. g. the level *obj_uid* as it is realised at the moment.

The "plottable" dataframe could then look like this:

| Index                | Component1 | Component2 | Component3 |
| -------------------- | ---------- | ---------- | ---------- |
| 2016-02-23 00:00:00  | 1.5        | 1.25       | 2.3        |
| 2016-02-23 01:00:00  | 1.6        | 1.35       | 2.4        |
| 2016-02-23 02:00:00  | 1.7        | 1.45       | 2.6        |
| ...                  | ...        | ...        | ...        |

If things (columns) need to be ordered/renamed for a stacked plot or something different, this could also be realised in the manipulation.

After this, it should be easily plottable with the pandas standard interface.

@uvchik : what do you think?

**Comment by uvchik** [comment]
I do not understand. I thought we already unstack the DataFrame but still have this `val` entry in the legend. But if there is a way to remove it from the column names I will totally agree!

The problem with the stackplot is different and reordering the columns does not help. I do want the lines to be plotted in a specific order e.g. `demand`, `battery load`, `export`. In a stacked plot the `demand` will be the base line and the `battery load` will be stacked on top and so on. That means that the `export` line is the last line that is plotted. If there is no `export` and no `battery load` all lines are together but you can only see the last line and this is the `export` line. So it is very confusing to read the plot. I want to stack the columns in one order and plot them in reverse order. This is very special and therefore something pandas can't do.

But still it is nice to make it possible to change the order :smile:

**Comment by ckaldemeyer** [comment]
> I do not understand. I thought we already unstack the DataFrame but still have this val entry in the legend. But if there is a way to remove it from the column names I will totally agree!
Maybe a hotfix for the current version of the outputlib that just renames the columns (removing "val) would be enough.

@s3pp : What's your opinion here?

> The problem with the stackplot is different and reordering the columns does not help. I do want the lines to be plotted in a specific order e.g. demand, battery load, export. In a stacked plot the demand will be the base line and the battery load will be stacked on top and so on. That means that the export line is the last line that is plotted. If there is no export and no battery load all lines are together but you can only see the last line and this is the export line. So it is very confusing to read the plot. I want to stack the columns in one order and plot them in reverse order. This is very special and therefore something pandas can't do.

You're right. This is indeed too special for pandas ;)

**Comment by s3pp** [comment]
I generated a new branch to solve this issue, but maybe there is a better way of doing this. I dropped the val in the slice unstacked method. It's working fine at first sight, but I don't know what happens if more than one level will be unstacked. Pushed to origin/features/fix-label-without-val-in-to_pandas

What do you think?

**Comment by uvchik** [comment]
Yes, this looks good. I do not overlook the side effects but this is exactly what I meant.

I thought it is not possible to unstack more than one level?

It works for my examples. If it works for all of you we can merge it.

**Comment by ckaldemeyer** [comment]
> Yes, this looks good. I do not overlook the side effects but this is exactly what I meant.
> I thought it is not possible to unstack more than one level?
You can also pass a list of levels. See: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.unstack.html

> It works for my examples. If it works for all of you we can merge it. Thank you :smile:
I am not using anything at the moment but I think if Martins renpass-gis plots, the storage-invest plots and the example_app plots are working, a merging should be fine.

**Comment by s3pp** [comment]
Huch, should we merge it back? The renpassG!S plots atm rely on the ResultsDataFrame only, thus the slice unstacked method is not called.

**Comment by uvchik** [comment]
I would merge it. It seems to work.

**Comment by s3pp** [comment]
Ok, done! : )

**Comment by s3pp** [comment]
As expected the legend entries consists now of only one word, definitely a slight improvement, but running the storage invest example one of the two first plots sometimes change in an unexpected way. The y-axis of the affected plot then shows a negative area up until - 200.000. This error seems to occur randomly. Although it seems to be related to this Fix, it is not clear why this should happen. As discussed with @uvchik I will not revert this commit by now. I will do so, if someone wants to trade back the legend entries for the y-axis starting at zero all the time.

**Comment by uvchik** [comment]
I solved the invest example and saved the results. Afterwards I created the DataFrame and plotted it.

I got no difference between commit 014d0c4e5c (before your changes) and commit fb892c4c3 (your changes).

Resolving it again makes a different but this has nothing to do with your changes.

**Comment by s3pp** [comment]
Ah, ok, that's interesting. So if it is not related to my changes, should I close this issue now?

**Comment by uvchik** [comment]
IMHO :+1:

**Comment by s3pp** [comment]
Thank you very much! :+1:
